import Foundation

struct Surah: Identifiable, Hashable {
    let id: Int
    let name: String
    let arabicName: String
}

struct SurahData {
    static let allSurahs: [Surah] = [
        Surah(id: 1, name: "Al-Fatiha - Die Eröffnung", arabicName: "الفاتحة"),
        Surah(id: 2, name: "Al-Baqara - Die Kuh", arabicName: "البقرة"),
        Surah(id: 3, name: "Al-Imran - Die Sippe Imrans", arabicName: "آل عمران"),
        Surah(id: 4, name: "An-Nisa - Die Frauen", arabicName: "النساء"),
        Surah(id: 5, name: "Al-Ma'ida - Der Tisch", arabicName: "المائدة"),
        Surah(id: 6, name: "Al-An'am - Das Vieh", arabicName: "الأنعام"),
        Surah(id: 7, name: "Al-A'raf - Die Höhen", arabicName: "الأعراف"),
        Surah(id: 8, name: "Al-Anfal - Die Beute", arabicName: "الأنفال"),
        Surah(id: 9, name: "At-Tauba - Die Reue", arabicName: "التوبة"),
        Surah(id: 10, name: "Yunus - Jona", arabicName: "يونس"),
        Surah(id: 11, name: "Hud - Hud", arabicName: "هود"),
        Surah(id: 12, name: "Yusuf - Josef", arabicName: "يوسف"),
        Surah(id: 13, name: "Ar-Ra'd - Der Donner", arabicName: "الرعد"),
        Surah(id: 14, name: "Ibrahim - Abraham", arabicName: "إبراهيم"),
        Surah(id: 15, name: "Al-Hijr - Das steinige Land", arabicName: "الحجر"),
        Surah(id: 16, name: "An-Nahl - Die Biene", arabicName: "النحل"),
        Surah(id: 17, name: "Al-Isra - Die Nachtreise", arabicName: "الإسراء"),
        Surah(id: 18, name: "Al-Kahf - Die Höhle", arabicName: "الكهف"),
        Surah(id: 19, name: "Maryam - Maria", arabicName: "مريم"),
        Surah(id: 20, name: "Ta-Ha - Ta-Ha", arabicName: "طه"),
        Surah(id: 21, name: "Al-Anbiya - Die Propheten", arabicName: "الأنبياء"),
        Surah(id: 22, name: "Al-Hajj - Die Pilgerfahrt", arabicName: "الحج"),
        Surah(id: 23, name: "Al-Mu'minun - Die Gläubigen", arabicName: "المؤمنون"),
        Surah(id: 24, name: "An-Nur - Das Licht", arabicName: "النور"),
        Surah(id: 25, name: "Al-Furqan - Die Unterscheidung", arabicName: "الفرقان"),
        Surah(id: 26, name: "Ash-Shu'ara - Die Dichter", arabicName: "الشعراء"),
        Surah(id: 27, name: "An-Naml - Die Ameisen", arabicName: "النمل"),
        Surah(id: 28, name: "Al-Qasas - Die Geschichte", arabicName: "القصص"),
        Surah(id: 29, name: "Al-Ankabut - Die Spinne", arabicName: "العنكبوت"),
        Surah(id: 30, name: "Ar-Rum - Die Römer", arabicName: "الروم"),
        Surah(id: 31, name: "Luqman - Luqman", arabicName: "لقمان"),
        Surah(id: 32, name: "As-Sajdah - Die Niederwerfung", arabicName: "السجدة"),
        Surah(id: 33, name: "Al-Ahzab - Die Parteien", arabicName: "الأحزاب"),
        Surah(id: 34, name: "Saba - Saba", arabicName: "سبأ"),
        Surah(id: 35, name: "Fatir - Der Schöpfer", arabicName: "فاطر"),
        Surah(id: 36, name: "Ya-Sin - Ya-Sin", arabicName: "يس"),
        Surah(id: 37, name: "As-Saffat - Die in Reih und Glied stehen", arabicName: "الصافات"),
        Surah(id: 38, name: "Sad - Sad", arabicName: "ص"),
        Surah(id: 39, name: "Az-Zumar - Die Scharen", arabicName: "الزمر"),
        Surah(id: 40, name: "Ghafir - Der Vergebende", arabicName: "غافر"),
        Surah(id: 41, name: "Fussilat - Erklärt", arabicName: "فصلت"),
        Surah(id: 42, name: "Ash-Shura - Die Beratung", arabicName: "الشورى"),
        Surah(id: 43, name: "Az-Zukhruf - Der Prunk", arabicName: "الزخرف"),
        Surah(id: 44, name: "Ad-Dukhan - Der Rauch", arabicName: "الدخان"),
        Surah(id: 45, name: "Al-Jathiyah - Die Kniende", arabicName: "الجاثية"),
        Surah(id: 46, name: "Al-Ahqaf - Die Sanddünen", arabicName: "الأحقاف"),
        Surah(id: 47, name: "Muhammad - Mohammed", arabicName: "محمد"),
        Surah(id: 48, name: "Al-Fath - Der Sieg", arabicName: "الفتح"),
        Surah(id: 49, name: "Al-Hujurat - Die Zimmer", arabicName: "الحجرات"),
        Surah(id: 50, name: "Qaf - Qaf", arabicName: "ق"),
        Surah(id: 51, name: "Adh-Dhariyat - Die Aufwirbelnden", arabicName: "الذاريات"),
        Surah(id: 52, name: "At-Tur - Der Berg", arabicName: "الطور"),
        Surah(id: 53, name: "An-Najm - Der Stern", arabicName: "النجم"),
        Surah(id: 54, name: "Al-Qamar - Der Mond", arabicName: "القمر"),
        Surah(id: 55, name: "Ar-Rahman - Der Allerbarmer", arabicName: "الرحمن"),
        Surah(id: 56, name: "Al-Waqi'ah - Das Ereignis", arabicName: "الواقعة"),
        Surah(id: 57, name: "Al-Hadid - Das Eisen", arabicName: "الحديد"),
        Surah(id: 58, name: "Al-Mujadila - Die Streitende", arabicName: "المجادلة"),
        Surah(id: 59, name: "Al-Hashr - Die Versammlung", arabicName: "الحشر"),
        Surah(id: 60, name: "Al-Mumtahanah - Die Geprüfte", arabicName: "الممتحنة"),
        Surah(id: 61, name: "As-Saff - Die Reihe", arabicName: "الصف"),
        Surah(id: 62, name: "Al-Jumu'ah - Der Freitag", arabicName: "الجمعة"),
        Surah(id: 63, name: "Al-Munafiqun - Die Heuchler", arabicName: "المنافقون"),
        Surah(id: 64, name: "At-Taghabun - Der gegenseitige Betrug", arabicName: "التغابن"),
        Surah(id: 65, name: "At-Talaq - Die Scheidung", arabicName: "الطلاق"),
        Surah(id: 66, name: "At-Tahrim - Das Verbot", arabicName: "التحريم"),
        Surah(id: 67, name: "Al-Mulk - Die Herrschaft", arabicName: "الملك"),
        Surah(id: 68, name: "Al-Qalam - Die Feder", arabicName: "القلم"),
        Surah(id: 69, name: "Al-Haqqah - Die Realität", arabicName: "الحاقة"),
        Surah(id: 70, name: "Al-Ma'arij - Die Himmelswege", arabicName: "المعارج"),
        Surah(id: 71, name: "Nuh - Noah", arabicName: "نوح"),
        Surah(id: 72, name: "Al-Jinn - Die Dschinn", arabicName: "الجن"),
        Surah(id: 73, name: "Al-Muzzammil - Der Eingehüllte", arabicName: "المزمل"),
        Surah(id: 74, name: "Al-Muddaththir - Der Überdeckte", arabicName: "المدثر"),
        Surah(id: 75, name: "Al-Qiyamah - Die Auferstehung", arabicName: "القيامة"),
        Surah(id: 76, name: "Al-Insan - Der Mensch", arabicName: "الإنسان"),
        Surah(id: 77, name: "Al-Mursalat - Die Gesandten", arabicName: "المرسلات"),
        Surah(id: 78, name: "An-Naba - Die Nachricht", arabicName: "النبأ"),
        Surah(id: 79, name: "An-Nazi'at - Die Entreißenden", arabicName: "النازعات"),
        Surah(id: 80, name: "Abasa - Er runzelte die Stirn", arabicName: "عبس"),
        Surah(id: 81, name: "At-Takwir - Das Einhüllen", arabicName: "التكوير"),
        Surah(id: 82, name: "Al-Infitar - Die Spaltung", arabicName: "الانفطار"),
        Surah(id: 83, name: "Al-Mutaffifin - Die das Maß verkürzen", arabicName: "المطففين"),
        Surah(id: 84, name: "Al-Inshiqaq - Die Spaltung", arabicName: "الانشقاق"),
        Surah(id: 85, name: "Al-Buruj - Die Türme", arabicName: "البروج"),
        Surah(id: 86, name: "At-Tariq - Der Nachtstern", arabicName: "الطارق"),
        Surah(id: 87, name: "Al-A'la - Der Höchste", arabicName: "الأعلى"),
        Surah(id: 88, name: "Al-Ghashiyah - Die Überwältigende", arabicName: "الغاشية"),
        Surah(id: 89, name: "Al-Fajr - Die Morgendämmerung", arabicName: "الفجر"),
        Surah(id: 90, name: "Al-Balad - Die Stadt", arabicName: "البلد"),
        Surah(id: 91, name: "Ash-Shams - Die Sonne", arabicName: "الشمس"),
        Surah(id: 92, name: "Al-Lail - Die Nacht", arabicName: "الليل"),
        Surah(id: 93, name: "Ad-Duha - Der Morgen", arabicName: "الضحى"),
        Surah(id: 94, name: "Ash-Sharh - Die Öffnung", arabicName: "الشرح"),
        Surah(id: 95, name: "At-Tin - Die Feige", arabicName: "التين"),
        Surah(id: 96, name: "Al-Alaq - Der Blutklumpen", arabicName: "العلق"),
        Surah(id: 97, name: "Al-Qadr - Die Bestimmung", arabicName: "القدر"),
        Surah(id: 98, name: "Al-Bayyina - Der klare Beweis", arabicName: "البينة"),
        Surah(id: 99, name: "Az-Zalzalah - Das Beben", arabicName: "الزلزلة"),
        Surah(id: 100, name: "Al-Adiyat - Die Rennenden", arabicName: "العاديات"),
        Surah(id: 101, name: "Al-Qari'ah - Das Pochen", arabicName: "القارعة"),
        Surah(id: 102, name: "At-Takathur - Die Vermehrung", arabicName: "التكاثر"),
        Surah(id: 103, name: "Al-Asr - Die Zeit", arabicName: "العصر"),
        Surah(id: 104, name: "Al-Humazah - Der Lästerer", arabicName: "الهمزة"),
        Surah(id: 105, name: "Al-Fil - Der Elefant", arabicName: "الفيل"),
        Surah(id: 106, name: "Quraysh - Die Quraisch", arabicName: "قريش"),
        Surah(id: 107, name: "Al-Ma'un - Die Hilfeleistung", arabicName: "الماعون"),
        Surah(id: 108, name: "Al-Kawthar - Die Fülle", arabicName: "الكوثر"),
        Surah(id: 109, name: "Al-Kafirun - Die Ungläubigen", arabicName: "الكافرون"),
        Surah(id: 110, name: "An-Nasr - Die Hilfe", arabicName: "النصر"),
        Surah(id: 111, name: "Al-Masad - Die Palmfasern", arabicName: "المسد"),
        Surah(id: 112, name: "Al-Ikhlas - Die Aufrichtigkeit", arabicName: "الإخلاص"),
        Surah(id: 113, name: "Al-Falaq - Das Frühlicht", arabicName: "الفلق"),
        Surah(id: 114, name: "An-Nas - Die Menschen", arabicName: "الناس")
    ]
}
