import Foundation

struct Surah: Identifiable, Hashable {
    let id: Int
    let name: String
    let englishName: String
}

struct SurahData {
    static let allSurahs: [Surah] = [
        Surah(id: 1, name: "Al-Fatiha", englishName: "The Opener"),
        Surah(id: 2, name: "Al-Baqarah", englishName: "The Cow"),
        Surah(id: 3, name: "Al-Imran", englishName: "Family of Imran"),
        Surah(id: 4, name: "An-Nisa", englishName: "The Women"),
        Surah(id: 5, name: "Al-Ma'idah", englishName: "The Table Spread"),
        Surah(id: 6, name: "Al-An'am", englishName: "The Cattle"),
        Surah(id: 7, name: "Al-A'raf", englishName: "The Heights"),
        Surah(id: 8, name: "Al-Anfal", englishName: "The Spoils of War"),
        Surah(id: 9, name: "At-Taubah", englishName: "The Repentance"),
        Surah(id: 10, name: "Yunus", englishName: "Jonah"),
        Surah(id: 11, name: "Hud", englishName: "Hud"),
        Surah(id: 12, name: "Yusuf", englishName: "Joseph"),
        Surah(id: 13, name: "Ar-Ra'd", englishName: "The Thunder"),
        Surah(id: 14, name: "Ibrahim", englishName: "Abraham"),
        Surah(id: 15, name: "Al-Hijr", englishName: "The Stoneland"),
        Surah(id: 16, name: "An-Nahl", englishName: "The Bee"),
        Surah(id: 17, name: "Al-Isra", englishName: "The Night Journey"),
        Surah(id: 18, name: "Al-Kahf", englishName: "The Cave"),
        Surah(id: 19, name: "Maryam", englishName: "Mary"),
        Surah(id: 20, name: "Ta-Ha", englishName: "Ta-Ha"),
        Surah(id: 21, name: "Al-Anbiya", englishName: "The Prophets"),
        Surah(id: 22, name: "Al-Hajj", englishName: "The Pilgrimage"),
        Surah(id: 23, name: "Al-Mu'minun", englishName: "The Believers"),
        Surah(id: 24, name: "An-Nur", englishName: "The Light"),
        Surah(id: 25, name: "Al-Furqan", englishName: "The Criterion"),
        Surah(id: 26, name: "Ash-Shu'ara", englishName: "The Poets"),
        Surah(id: 27, name: "An-Naml", englishName: "The Ant"),
        Surah(id: 28, name: "Al-Qasas", englishName: "The Narrative"),
        Surah(id: 29, name: "Al-Ankabut", englishName: "The Spider"),
        Surah(id: 30, name: "Ar-Rum", englishName: "The Romans"),
        Surah(id: 31, name: "Luqman", englishName: "Luqman"),
        Surah(id: 32, name: "As-Sajdah", englishName: "The Prostration"),
        Surah(id: 33, name: "Al-Ahzab", englishName: "The Confederates"),
        Surah(id: 34, name: "Saba", englishName: "Sheba"),
        Surah(id: 35, name: "Fatir", englishName: "The Originator"),
        Surah(id: 36, name: "Ya-Sin", englishName: "Ya Sin"),
        Surah(id: 37, name: "As-Saffat", englishName: "Those Who Set the Ranks"),
        Surah(id: 38, name: "Sad", englishName: "The Letter Sad"),
        Surah(id: 39, name: "Az-Zumar", englishName: "The Troops"),
        Surah(id: 40, name: "Ghafir", englishName: "The Forgiver"),
        Surah(id: 41, name: "Fussilat", englishName: "Explained in Detail"),
        Surah(id: 42, name: "Ash-Shura", englishName: "The Consultation"),
        Surah(id: 43, name: "Az-Zukhruf", englishName: "The Ornaments of Gold"),
        Surah(id: 44, name: "Ad-Dukhan", englishName: "The Smoke"),
        Surah(id: 45, name: "Al-Jathiyah", englishName: "The Crouching"),
        Surah(id: 46, name: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills"),
        Surah(id: 47, name: "Muhammad", englishName: "Muhammad"),
        Surah(id: 48, name: "Al-Fath", englishName: "The Victory"),
        Surah(id: 49, name: "Al-Hujurat", englishName: "The Private Chambers"),
        Surah(id: 50, name: "Qaf", englishName: "The Letter Qaf"),
        Surah(id: 51, name: "Adh-Dhariyat", englishName: "The Winnowing Winds"),
        Surah(id: 52, name: "At-Tur", englishName: "The Mount"),
        Surah(id: 53, name: "An-Najm", englishName: "The Star"),
        Surah(id: 54, name: "Al-Qamar", englishName: "The Moon"),
        Surah(id: 55, name: "Ar-Rahman", englishName: "The Beneficent"),
        Surah(id: 56, name: "Al-Waqi'ah", englishName: "The Inevitable"),
        Surah(id: 57, name: "Al-Hadid", englishName: "The Iron"),
        Surah(id: 58, name: "Al-Mujadila", englishName: "The Pleading Woman"),
        Surah(id: 59, name: "Al-Hashr", englishName: "The Exile"),
        Surah(id: 60, name: "Al-Mumtahanah", englishName: "She That Is to Be Examined"),
        Surah(id: 61, name: "As-Saff", englishName: "The Ranks"),
        Surah(id: 62, name: "Al-Jumu'ah", englishName: "The Congregation"),
        Surah(id: 63, name: "Al-Munafiqun", englishName: "The Hypocrites"),
        Surah(id: 64, name: "At-Taghabun", englishName: "The Mutual Disillusion"),
        Surah(id: 65, name: "At-Talaq", englishName: "The Divorce"),
        Surah(id: 66, name: "At-Tahrim", englishName: "The Prohibition"),
        Surah(id: 67, name: "Al-Mulk", englishName: "The Sovereignty"),
        Surah(id: 68, name: "Al-Qalam", englishName: "The Pen"),
        Surah(id: 69, name: "Al-Haqqah", englishName: "The Reality"),
        Surah(id: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways"),
        Surah(id: 71, name: "Nuh", englishName: "Noah"),
        Surah(id: 72, name: "Al-Jinn", englishName: "The Jinn"),
        Surah(id: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One"),
        Surah(id: 74, name: "Al-Muddaththir", englishName: "The Cloaked One"),
        Surah(id: 75, name: "Al-Qiyamah", englishName: "The Resurrection"),
        Surah(id: 76, name: "Al-Insan", englishName: "The Man"),
        Surah(id: 77, name: "Al-Mursalat", englishName: "The Emissaries"),
        Surah(id: 78, name: "An-Naba", englishName: "The Tidings"),
        Surah(id: 79, name: "An-Nazi'at", englishName: "Those Who Drag Forth"),
        Surah(id: 80, name: "Abasa", englishName: "He Frowned"),
        Surah(id: 81, name: "At-Takwir", englishName: "The Overthrowing"),
        Surah(id: 82, name: "Al-Infitar", englishName: "The Cleaving"),
        Surah(id: 83, name: "Al-Mutaffifin", englishName: "The Defrauding"),
        Surah(id: 84, name: "Al-Inshiqaq", englishName: "The Sundering"),
        Surah(id: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars"),
        Surah(id: 86, name: "At-Tariq", englishName: "The Nightcommer"),
        Surah(id: 87, name: "Al-A'la", englishName: "The Most High"),
        Surah(id: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming"),
        Surah(id: 89, name: "Al-Fajr", englishName: "The Dawn"),
        Surah(id: 90, name: "Al-Balad", englishName: "The City"),
        Surah(id: 91, name: "Ash-Shams", englishName: "The Sun"),
        Surah(id: 92, name: "Al-Lail", englishName: "The Night"),
        Surah(id: 93, name: "Ad-Duha", englishName: "The Morning Hours"),
        Surah(id: 94, name: "Ash-Sharh", englishName: "The Relief"),
        Surah(id: 95, name: "At-Tin", englishName: "The Fig"),
        Surah(id: 96, name: "Al-Alaq", englishName: "The Clot"),
        Surah(id: 97, name: "Al-Qadr", englishName: "The Power"),
        Surah(id: 98, name: "Al-Bayyina", englishName: "The Clear Proof"),
        Surah(id: 99, name: "Az-Zalzalah", englishName: "The Earthquake"),
        Surah(id: 100, name: "Al-Adiyat", englishName: "The Courser"),
        Surah(id: 101, name: "Al-Qari'ah", englishName: "The Calamity"),
        Surah(id: 102, name: "At-Takathur", englishName: "The Rivalry in World Increase"),
        Surah(id: 103, name: "Al-Asr", englishName: "The Declining Day"),
        Surah(id: 104, name: "Al-Humazah", englishName: "The Traducer"),
        Surah(id: 105, name: "Al-Fil", englishName: "The Elephant"),
        Surah(id: 106, name: "Quraysh", englishName: "Quraysh"),
        Surah(id: 107, name: "Al-Ma'un", englishName: "The Small Kindnesses"),
        Surah(id: 108, name: "Al-Kawthar", englishName: "The Abundance"),
        Surah(id: 109, name: "Al-Kafirun", englishName: "The Disbelievers"),
        Surah(id: 110, name: "An-Nasr", englishName: "The Divine Support"),
        Surah(id: 111, name: "Al-Masad", englishName: "The Palm Fiber"),
        Surah(id: 112, name: "Al-Ikhlas", englishName: "The Sincerity"),
        Surah(id: 113, name: "Al-Falaq", englishName: "The Daybreak"),
        Surah(id: 114, name: "An-Nas", englishName: "Mankind")
    ]
}
