import Foundation

struct Surah: Identifiable, Hashable {
    let id: Int
    let name: String
    let arabicName: String
    let germanName: String
}

struct SurahData {
    static let allSurahs: [Surah] = [
        Surah(id: 1, name: "al-Fātiḥa", arabicName: "الفاتحة", germanName: "Die Eröffnung"),
        Surah(id: 2, name: "al-Baqara", arabicName: "البقرة", germanName: "Die Kuh"),
        Surah(id: 3, name: "Āl ʿImrān", arabicName: "آل عمران", germanName: "Die Sippe Imrans"),
        Surah(id: 4, name: "an-Nisāʾ", arabicName: "النّساء", germanName: "Die Frauen"),
        Surah(id: 5, name: "al-Māʾida", arabicName: "المائدة", germanName: "Der Tisch"),
        Surah(id: 6, name: "al-Anʿām", arabicName: "الأنعام", germanName: "Das Vieh"),
        Surah(id: 7, name: "al-A'raf", arabicName: "الأعراف", germanName: "Die Höhen"),
        Surah(id: 8, name: "al-Anfāl", arabicName: "الأنفال", germanName: "Die Beute"),
        Surah(id: 9, name: "at-Tauba", arabicName: "التوبة", germanName: "Die Buße"),
        Surah(id: 10, name: "Yūnus", arabicName: "يونس", germanName: "Jonas"),
        Surah(id: 11, name: "Hūd", arabicName: "هود", germanName: "Hud"),
        Surah(id: 12, name: "Yūsuf", arabicName: "يوسف", germanName: "Joseph"),
        Surah(id: 13, name: "ar-Raʿd", arabicName: "الرّعد", germanName: "Der Donner"),
        Surah(id: 14, name: "Ibrāhīm", arabicName: "إبراهيم", germanName: "Abraham"),
        Surah(id: 15, name: "al-Ḥiǧr", arabicName: "الحجر", germanName: "Das steinige Land"),
        Surah(id: 16, name: "an-Naḥl", arabicName: "النّحل", germanName: "Die Biene"),
        Surah(id: 17, name: "al-Isrāʾ", arabicName: "الإسراء", germanName: "Die nächtliche Reise"),
        Surah(id: 18, name: "al-Kahf", arabicName: "الكهف", germanName: "Die Höhle"),
        Surah(id: 19, name: "Maryam", arabicName: "مريم", germanName: "Maria"),
        Surah(id: 20, name: "Ṭā-Hā", arabicName: "طه", germanName: "Ta Ha"),
        Surah(id: 21, name: "al-Anbiyāʾ", arabicName: "الأنبياء", germanName: "Die Propheten"),
        Surah(id: 22, name: "al-Ḥaǧǧ", arabicName: "الحجّ", germanName: "Die Wallfahrt"),
        Surah(id: 23, name: "al-Muʾminūn", arabicName: "المؤمنون", germanName: "Die Gläubigen"),
        Surah(id: 24, name: "an-Nūr", arabicName: "النّور", germanName: "Das Licht"),
        Surah(id: 25, name: "al-Furqān", arabicName: "الفرقان", germanName: "Die Rettung"),
        Surah(id: 26, name: "aš-Šuʿarāʾ", arabicName: "الشّعراء", germanName: "Die Dichter"),
        Surah(id: 27, name: "an-Naml", arabicName: "النّمل", germanName: "Die Ameisen"),
        Surah(id: 28, name: "al-Qasas", arabicName: "القصص", germanName: "Die Geschichte"),
        Surah(id: 29, name: "al-ʿAnkabūt", arabicName: "العنكبوت", germanName: "Die Spinne"),
        Surah(id: 30, name: "ar-Rūm", arabicName: "الرّوم", germanName: "Die Römer"),
        Surah(id: 31, name: "Luqman", arabicName: "لقمان", germanName: "Luqman"),
        Surah(id: 32, name: "as-Saǧda", arabicName: "السّجدة", germanName: "Die Niederwerfung"),
        Surah(id: 33, name: "al-Aḥzāb", arabicName: "الأحزاب", germanName: "Die Gruppen"),
        Surah(id: 34, name: "Sabaʾ", arabicName: "سبأ", germanName: "Die Sabäer"),
        Surah(id: 35, name: "Fāṭir", arabicName: "فاطر", germanName: "Der Schöpfer"),
        Surah(id: 36, name: "Ya-Sīn", arabicName: "يس", germanName: "Ya-Sin"),
        Surah(id: 37, name: "aṣ-Ṣāffāt", arabicName: "الصّافات", germanName: "Die in Reih und Glied stehen"),
        Surah(id: 38, name: "Ṣād", arabicName: "ص", germanName: "Sad"),
        Surah(id: 39, name: "az-Zumar", arabicName: "الزّمر", germanName: "Die Scharen"),
        Surah(id: 40, name: "Ġāfir", arabicName: "غافر", germanName: "Der Vergebende"),
        Surah(id: 41, name: "Fuṣṣilat", arabicName: "فصّلت", germanName: "Auseinandergesetzt sind"),
        Surah(id: 42, name: "aš-Šūrā", arabicName: "الشّورى", germanName: "Die Beratung"),
        Surah(id: 43, name: "az-Zuḫruf", arabicName: "الزّخرف", germanName: "Der Prunk"),
        Surah(id: 44, name: "ad-Duḫān", arabicName: "الدّخان", germanName: "Der Rauch"),
        Surah(id: 45, name: "al-Ǧāṯiya", arabicName: "الجاثية", germanName: "Das Knien"),
        Surah(id: 46, name: "al-Aḥqāf", arabicName: "الأحقاف", germanName: "Die Dünen"),
        Surah(id: 47, name: "Muḥammad", arabicName: "محمّد", germanName: "Mohammed"),
        Surah(id: 48, name: "al-Fatḥ", arabicName: "الفتح", germanName: "Der Erfolg"),
        Surah(id: 49, name: "al-Ḥuǧurāt", arabicName: "الحجرات", germanName: "Die Gemächer"),
        Surah(id: 50, name: "Qāf", arabicName: "ق", germanName: "Qaf"),
        Surah(id: 51, name: "aḏ-Ḏāriyāt", arabicName: "الذّاريات", germanName: "Das Aufwirbeln"),
        Surah(id: 52, name: "at-Tūr", arabicName: "الطّور", germanName: "Der Berg"),
        Surah(id: 53, name: "an-Naǧm", arabicName: "النّجْم", germanName: "Der Stern"),
        Surah(id: 54, name: "al-Qamar", arabicName: "القمر", germanName: "Der Mond"),
        Surah(id: 55, name: "ar-Raḥmān", arabicName: "الرّحْمن", germanName: "Der Barmherzige"),
        Surah(id: 56, name: "al-Wāqiʿa", arabicName: "الواقعة", germanName: "Die hereinbrechende Katastrophe"),
        Surah(id: 57, name: "al-Ḥadīd", arabicName: "الحديد", germanName: "Das Eisen"),
        Surah(id: 58, name: "al-Muǧādala", arabicName: "المجادلة", germanName: "Der Streit"),
        Surah(id: 59, name: "al-Ḥašr", arabicName: "الحشْر", germanName: "Die Versammlung"),
        Surah(id: 60, name: "al-Mumtaḥina", arabicName: "الممتحنة", germanName: "Die Prüfung"),
        Surah(id: 61, name: "aṣ-Ṣaff", arabicName: "الصّفّ", germanName: "Reih und Glied"),
        Surah(id: 62, name: "al-Ǧumʿa", arabicName: "الجمعة", germanName: "Der Freitag"),
        Surah(id: 63, name: "al-Munāfiqūn", arabicName: "المنافقون", germanName: "Die Heuchler"),
        Surah(id: 64, name: "at-Taġābun", arabicName: "التّغابن", germanName: "Die Übervorteilung"),
        Surah(id: 65, name: "aṭ-Ṭalāq", arabicName: "الطّلاق", germanName: "Die Scheidung"),
        Surah(id: 66, name: "at-Taḥrīm", arabicName: "التّحريم", germanName: "Das Verbot"),
        Surah(id: 67, name: "al-Mulk", arabicName: "الملك", germanName: "Die Königsherrschaft"),
        Surah(id: 68, name: "al-Qalam", arabicName: "القلم", germanName: "Die Schreibfeder"),
        Surah(id: 69, name: "al-Ḥāqqa", arabicName: "الحاقّة", germanName: "Die Wahrheit"),
        Surah(id: 70, name: "al-Maʿāriǧ", arabicName: "المعارج", germanName: "Die Himmelsleiter"),
        Surah(id: 71, name: "Nūḥ", arabicName: "نوح", germanName: "Noah"),
        Surah(id: 72, name: "al-Ǧinn", arabicName: "الجنّ", germanName: "Die Jinn"),
        Surah(id: 73, name: "al-Muzzammil", arabicName: "المزمّل", germanName: "Der sich eingehüllt hat"),
        Surah(id: 74, name: "al-Mudaṯṯir", arabicName: "المدثّر", germanName: "Der sich zugedeckt hat"),
        Surah(id: 75, name: "al-Qiyāma", arabicName: "القيامة", germanName: "Die Auferstehung"),
        Surah(id: 76, name: "al-Insān", arabicName: "الإٍنسان", germanName: "Der Mensch"),
        Surah(id: 77, name: "al-Mursalāt", arabicName: "المرسلات", germanName: "Die Gesandten"),
        Surah(id: 78, name: "an-Nabaʾ", arabicName: "النّبأ", germanName: "Die Ankündigung"),
        Surah(id: 79, name: "an-Nāziʿāt", arabicName: "النّازعات", germanName: "Die ausziehen"),
        Surah(id: 80, name: "ʿAbasa", arabicName: "عبس", germanName: "Er zog die Stirne kraus"),
        Surah(id: 81, name: "at-Takwīr", arabicName: "التّكوير", germanName: "Das Einhüllen"),
        Surah(id: 82, name: "al-Infiṭār", arabicName: "الانفطار", germanName: "Die Spaltung"),
        Surah(id: 83, name: "al-Muṭaffifīn", arabicName: "المطفّفين", germanName: "Die Betrüger"),
        Surah(id: 84, name: "al-Inšiqāq", arabicName: "الانشقاق", germanName: "Das Zerbrechen"),
        Surah(id: 85, name: "al-Burūǧ", arabicName: "البروج", germanName: "Die Türme"),
        Surah(id: 86, name: "aṭ-Ṭāriq", arabicName: "الطّارق", germanName: "Der bei Nacht kommende"),
        Surah(id: 87, name: "al-Aʿlā", arabicName: "الأعلى", germanName: "Der Allerhöchste"),
        Surah(id: 88, name: "al-Ġāšiya", arabicName: "الغاشية", germanName: "Die zudecken wird"),
        Surah(id: 89, name: "al-Faǧr", arabicName: "الفجر", germanName: "Die Morgendämmerung"),
        Surah(id: 90, name: "al-Balad", arabicName: "البلد", germanName: "Die Stadt"),
        Surah(id: 91, name: "aš-Šams", arabicName: "الشّمس", germanName: "Die Sonne"),
        Surah(id: 92, name: "al-Lail", arabicName: "الليل", germanName: "Die Nacht"),
        Surah(id: 93, name: "aḍ-Ḍuḥā", arabicName: "الضحى", germanName: "Der Morgen"),
        Surah(id: 94, name: "aš-Šarḥ", arabicName: "الشرح", germanName: "Das Weiten"),
        Surah(id: 95, name: "at-Tīn", arabicName: "التِّينِ", germanName: "Die Feigenbäume"),
        Surah(id: 96, name: "al-ʿAlaq", arabicName: "العَلَق", germanName: "Der Blutklumpen"),
        Surah(id: 97, name: "al-Qadr", arabicName: "الْقَدْرِ", germanName: "Die Bestimmung"),
        Surah(id: 98, name: "al-Bayyina", arabicName: "الْبَيِّنَةُ", germanName: "Der klare Beweis"),
        Surah(id: 99, name: "az-Zalzala", arabicName: "الزلزلة", germanName: "Das Beben"),
        Surah(id: 100, name: "al-ʿĀdiyāt", arabicName: "العاديات", germanName: "Das Laufen"),
        Surah(id: 101, name: "al-Qāriʿa", arabicName: "القارعة", germanName: "Die Polternde"),
        Surah(id: 102, name: "at-Takāṯur", arabicName: "التكاثر", germanName: "Die Sucht mehr zu haben"),
        Surah(id: 103, name: "al-ʿAsr", arabicName: "العصر", germanName: "Der Nachmittag"),
        Surah(id: 104, name: "al-Humaza", arabicName: "الهُمَزة", germanName: "Der Stichler"),
        Surah(id: 105, name: "al-Fīl", arabicName: "الْفِيلِ", germanName: "Der Elefant"),
        Surah(id: 106, name: "Quraiš", arabicName: "قُرَيْشٍ", germanName: "Die Quraisch"),
        Surah(id: 107, name: "al-Māʿūn", arabicName: "الْمَاعُونَ", germanName: "Die Hilfeleistung"),
        Surah(id: 108, name: "al-Kauṯar", arabicName: "الكوثر", germanName: "Die Fülle"),
        Surah(id: 109, name: "al-Kāfirūn", arabicName: "الْكَافِرُونَ", germanName: "Die Ungläubigen"),
        Surah(id: 110, name: "an-Naṣr", arabicName: "النصر", germanName: "Die Hilfe"),
        Surah(id: 111, name: "al-Masad", arabicName: "المسد", germanName: "Der Palmfaserstrick"),
        Surah(id: 112, name: "al-Iḫlāṣ", arabicName: "الإخلاص", germanName: "Die Aufrichtigkeit"),
        Surah(id: 113, name: "al-Falaq", arabicName: "الْفَلَقِ", germanName: "Das Frühlicht"),
        Surah(id: 114, name: "an-Nās", arabicName: "النَّاسِ", germanName: "Die Menschheit")
    ]
}
